name: sphinx2ghpages_geonode_guide

on:
  push:
    branches: [ master ]

jobs:
  build_docs:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Environment Setup
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: envSphinx
          environment-file: packages/environment.yml
          auto-activate-base: false

      - name: Install additional dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./packages/requirements.txt

      - name: Make Docs
        run: |
          make -C docs clean
          make -C docs html

      - name: Create dist repo and commit
        run: |
          cd docs/build/html
          git init
          touch .nojekyll
          git add -A
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git config --global --add safe.directory /github/workspace/docs/build/html
          git commit -m "deploy"

      - name: Push to gh-pages branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/build/html
        